{
    'name': 'Tags Inheritance',
    'version': '1.0',
    'category': 'Sales/CRM',
    'summary': 'Extends tag functionality for customers, vendors and products',
    'depends': [
        'base',
        'crm',
        'sales_team',
        'product',
        'account',
        'purchase',
    ],
    'data': [
        'security/tag_security.xml',
        'security/ir.model.access.csv',
        'views/crm_tag_tree_inherit.xml',
        'views/res_partner_views.xml',
        'views/res_users_views.xml',
        'views/res_company_views.xml',
        'views/product_template_views.xml',
        'views/product_tag_form_view.xml',
        'views/account_tag_views.xml',
        'views/tag_dashboard_views.xml',
    ],
    'demo': [
        'demo/tag_demo.xml',
    ],
    'images': [
        'static/description/icon.png',
        'static/description/screenshot1.png',
        'static/description/screenshot2.png',
        'static/description/screenshot3.png',
        'static/description/screenshot4.png',
        'static/description/screenshot5.png',
        'static/description/screenshot6.png',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
